name: Deploy to Heroku GANDU

on: 
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: 5hojib/heroku-deploy-action@v2
        with:
          heroku_api_key: ''
          heroku_app_name: 'rd729hsis'
          heroku_email: ''
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
